/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Liveness probe (process up).
         */
        get: operations["health_live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness probe (DB + models).
         */
        get: operations["health_ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus Metrics
         * @description Plain-text Prometheus exposition for hospital ops / Triton-style scraping.
         */
        get: operations["prometheus_metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Studies */
        post: operations["upload_studies_api_v1_studies_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Studies */
        get: operations["list_studies_api_v1_studies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Study */
        get: operations["get_study_api_v1_studies__study_uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/seed-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Demo */
        post: operations["seed_demo_api_v1_studies_seed_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{series_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Series */
        get: operations["get_series_api_v1_series__series_uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{series_uid}/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instances */
        get: operations["list_instances_api_v1_series__series_uid__instances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{series_uid}/frames/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Frame */
        get: operations["get_frame_api_v1_series__series_uid__frames__idx__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{series_uid}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thumbnail */
        get: operations["get_thumbnail_api_v1_series__series_uid__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Ready */
        get: operations["model_ready_api_v1_models__model_id__ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_api_v1_models__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Model */
        patch: operations["patch_model_api_v1_models__model_id__patch"];
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_v1_tasks__task_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Events */
        get: operations["task_events_api_v1_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Task */
        post: operations["cancel_task_api_v1_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Task */
        post: operations["retry_task_api_v1_tasks__task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Report */
        post: operations["create_report_api_v1_tasks__task_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/mask-frames/{slice_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mask Frame */
        get: operations["get_mask_frame_api_v1_tasks__task_id__mask_frames__slice_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_v1_tasks__task_id__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactRef */
        ArtifactRef: {
            /** Name */
            name: string;
            /** Uri */
            uri: string;
            /**
             * Media Type
             * @default application/octet-stream
             */
            media_type: string;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Url */
            url?: string | null;
        };
        /** Body_upload_studies_api_v1_studies_upload_post */
        Body_upload_studies_api_v1_studies_upload_post: {
            /** Files */
            files: string[];
        };
        /** ClassificationPrediction */
        ClassificationPrediction: {
            /** Label */
            label: string;
            /** Probability */
            probability: number;
        };
        /** DailyTaskPoint */
        DailyTaskPoint: {
            /** Date */
            date: string;
            /** Total */
            total: number;
            /**
             * Succeeded
             * @default 0
             */
            succeeded: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
        };
        /** DetectionBox */
        DetectionBox: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /** Slice Index */
            slice_index?: number | null;
            /** Bbox */
            bbox?: number[] | null;
            /** Bbox3D */
            bbox3d?: number[] | null;
            /** Diameter Mm */
            diameter_mm?: number | null;
        };
        /** FindingReviewItem */
        FindingReviewItem: {
            /** Finding Id */
            finding_id: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "accepted" | "rejected" | "corrected";
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
            queue: components["schemas"]["QueueStatus"];
            /** Models */
            models: number;
        };
        /** InferenceResult */
        InferenceResult: {
            /** Type */
            type: ("segmentation" | "detection" | "classification") | string;
            /** Series Uid */
            series_uid: string;
            /** Model Id */
            model_id: string;
            /** Model Version */
            model_version: string;
            /** Runtime Ms */
            runtime_ms: number;
            /** Summary */
            summary: string;
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactRef"][];
            /** Masks */
            masks?: components["schemas"]["MaskArtifact"][];
            /** Boxes */
            boxes?: components["schemas"]["DetectionBox"][];
            /** Predictions */
            predictions?: components["schemas"]["ClassificationPrediction"][];
            /** Cam Overlay Uri */
            cam_overlay_uri?: string | null;
        };
        /** InstanceItem */
        InstanceItem: {
            /** Sop Uid */
            sop_uid: string;
            /** Instance Number */
            instance_number: number;
            /**
             * Slice Index
             * @default 0
             */
            slice_index: number;
            /** Slice Position */
            slice_position?: number | null;
            /** Rows */
            rows?: number | null;
            /** Cols */
            cols?: number | null;
            /** Frame Url */
            frame_url: string;
            /** Wadouri */
            wadouri: string;
        };
        /** InstanceListResponse */
        InstanceListResponse: {
            /** Items */
            items: components["schemas"]["InstanceItem"][];
            /** Total */
            total: number;
            series: components["schemas"]["SeriesSummary"];
        };
        /** LiveHealthResponse */
        LiveHealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** MaskArtifact */
        MaskArtifact: {
            /** Label Id */
            label_id: number;
            /** Label Name */
            label_name: string;
            /** Color */
            color: string;
            /** Encoding */
            encoding: string;
            /** Uri */
            uri: string;
            /** Volume Mm3 */
            volume_mm3?: number | null;
            /** Dice */
            dice?: number | null;
            /** Slice Indices */
            slice_indices?: number[];
        };
        /** ModelListResponse */
        ModelListResponse: {
            /** Items */
            items: components["schemas"]["ModelSpec"][];
            /** Total */
            total: number;
        };
        /** ModelMetricItem */
        ModelMetricItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Task Type */
            task_type: ("segmentation" | "detection" | "classification") | string;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** ModelOutputSpec */
        ModelOutputSpec: {
            /** Name */
            name: string;
            /** Result Type */
            result_type: ("segmentation" | "detection" | "classification") | string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** ModelPatchRequest */
        ModelPatchRequest: {
            /** Enabled */
            enabled?: boolean | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            } | null;
        };
        /** ModelReadyResponse */
        ModelReadyResponse: {
            /** Model Id */
            model_id: string;
            /** Ready */
            ready: boolean;
            /** Enabled */
            enabled: boolean;
            /** Version */
            version: string;
            /** Message */
            message: string;
        };
        /** ModelSpec */
        ModelSpec: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Task Type */
            task_type: ("segmentation" | "detection" | "classification") | string;
            /** Modalities */
            modalities: string[];
            /** Body Parts */
            body_parts: string[];
            /** Description */
            description: string;
            /** Input Constraints */
            input_constraints?: {
                [key: string]: unknown;
            };
            /** Params Schema */
            params_schema?: {
                [key: string]: unknown;
            };
            /** Outputs */
            outputs?: components["schemas"]["ModelOutputSpec"][];
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /**
             * Expected Latency Ms
             * @default 0
             */
            expected_latency_ms: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Tags */
            tags?: string[];
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            };
        };
        /** ModelUsageItem */
        ModelUsageItem: {
            /** Model Id */
            model_id: string;
            /** Name */
            name: string;
            /** Task Type */
            task_type: ("segmentation" | "detection" | "classification") | string;
            /** Total */
            total: number;
            /** Succeeded */
            succeeded: number;
            /** Failed */
            failed: number;
            /** Avg Runtime Ms */
            avg_runtime_ms?: number | null;
        };
        /** OverviewKpis */
        OverviewKpis: {
            /** Study Count */
            study_count: number;
            /** Model Count */
            model_count: number;
            /** Today Tasks */
            today_tasks: number;
            /**
             * Avg Dice
             * @description Catalog mean Dice across segmentation models
             */
            avg_dice: number;
            /**
             * Success Rate
             * @description succeeded / (succeeded + failed); null when no finished tasks
             */
            success_rate?: number | null;
            /**
             * Failed Today
             * @default 0
             */
            failed_today: number;
        };
        /** OverviewStats */
        OverviewStats: {
            kpis: components["schemas"]["OverviewKpis"];
            /** Model Metrics */
            model_metrics?: components["schemas"]["ModelMetricItem"][];
            /** Model Distribution */
            model_distribution?: {
                [key: string]: number;
            };
            /** Daily Tasks */
            daily_tasks?: components["schemas"]["DailyTaskPoint"][];
            /** Model Usage */
            model_usage?: components["schemas"]["ModelUsageItem"][];
            /** Recent Tasks */
            recent_tasks?: components["schemas"]["TaskSummary"][];
            queue?: components["schemas"]["QueueStatus"];
            /**
             * Registered Models
             * @default 0
             */
            registered_models: number;
        };
        /** Page[StudySummary] */
        Page_StudySummary_: {
            /** Items */
            items: components["schemas"]["StudySummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[TaskSummary] */
        Page_TaskSummary_: {
            /** Items */
            items: components["schemas"]["TaskSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** QueueStatus */
        QueueStatus: {
            /** Queued */
            queued: number;
            /** Running */
            running: number;
            /** Max Concurrency */
            max_concurrency: number;
        };
        /** ReadyHealthResponse */
        ReadyHealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Database */
            database: string;
            /** Models */
            models: number;
            queue: components["schemas"]["QueueStatus"];
        };
        /** ReportArtifact */
        ReportArtifact: {
            /** Name */
            name: string;
            /** Uri */
            uri: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Url */
            url?: string | null;
        };
        /**
         * ReportCreateRequest
         * @description Generate structured report (+ optional DICOM exports) from selected findings.
         */
        ReportCreateRequest: {
            /** Finding Ids */
            finding_ids?: string[];
            /** Reviews */
            reviews?: components["schemas"]["FindingReviewItem"][];
            /**
             * Export Seg
             * @default true
             */
            export_seg: boolean;
            /**
             * Export Sr
             * @default true
             */
            export_sr: boolean;
            /**
             * Export Gsps
             * @default true
             */
            export_gsps: boolean;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Report Id */
            report_id: string;
            /** Task Id */
            task_id: string;
            /** Model Id */
            model_id: string;
            /** Model Version */
            model_version: string;
            /** Finding Ids */
            finding_ids?: string[];
            /** Text */
            text: string;
            /** Artifacts */
            artifacts?: components["schemas"]["ReportArtifact"][];
        };
        /** SeriesSummary */
        SeriesSummary: {
            /** Series Uid */
            series_uid: string;
            /** Study Uid */
            study_uid: string;
            /** Modality */
            modality?: string | null;
            /** Body Part */
            body_part?: string | null;
            /** Description */
            description?: string | null;
            /** Series Number */
            series_number?: number | null;
            /** Rows */
            rows?: number | null;
            /** Cols */
            cols?: number | null;
            /**
             * Num Instances
             * @default 0
             */
            num_instances: number;
            /** Spacing */
            spacing?: (number | null)[] | null;
            /**
             * Is Phantom
             * @default false
             */
            is_phantom: boolean;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * StudyLastTask
         * @description Latest inference task for a study (compact; for data-table AI status).
         */
        StudyLastTask: {
            /** Task Id */
            task_id: string;
            /** Model Id */
            model_id: string;
            /** Model Name */
            model_name?: string | null;
            /** Status */
            status: ("queued" | "running" | "succeeded" | "failed" | "canceled") | string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Message */
            message?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** StudySummary */
        StudySummary: {
            /** Study Uid */
            study_uid: string;
            /** Patient Id */
            patient_id?: string | null;
            /** Patient Name */
            patient_name?: string | null;
            /** Patient Sex */
            patient_sex?: string | null;
            /** Patient Age */
            patient_age?: string | null;
            /** Study Date */
            study_date?: string | null;
            /** Study Description */
            study_description?: string | null;
            /** Modality */
            modality?: string | null;
            /** Body Part */
            body_part?: string | null;
            /** Institution */
            institution?: string | null;
            /**
             * Num Series
             * @default 0
             */
            num_series: number;
            /**
             * Num Instances
             * @default 0
             */
            num_instances: number;
            /** Created At */
            created_at?: string | null;
            /** Series */
            series?: components["schemas"]["SeriesSummary"][] | null;
            last_task?: components["schemas"]["StudyLastTask"] | null;
        };
        /** StudyUploadResponse */
        StudyUploadResponse: {
            /** Items */
            items: components["schemas"]["StudySummary"][];
            /** Total */
            total: number;
        };
        /** TaskCreateRequest */
        TaskCreateRequest: {
            /** Series Uid */
            series_uid: string;
            /** Model Id */
            model_id: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** TaskCreateResponse */
        TaskCreateResponse: {
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
        };
        /** TaskLog */
        TaskLog: {
            /** Level */
            level: string;
            /** Stage */
            stage?: string | null;
            /** Message */
            message: string;
            /** Created At */
            created_at?: string | null;
        };
        /** TaskSummary */
        TaskSummary: {
            /** Task Id */
            task_id: string;
            /** Series Uid */
            series_uid: string;
            /** Study Uid */
            study_uid?: string | null;
            /** Model Id */
            model_id: string;
            /** Model Version */
            model_version?: string | null;
            /** Patient Name */
            patient_name?: string | null;
            /** Patient Id */
            patient_id?: string | null;
            /** Modality */
            modality?: string | null;
            /** Study Description */
            study_description?: string | null;
            /** Model Name */
            model_name?: string | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Status */
            status: ("queued" | "running" | "succeeded" | "failed" | "canceled") | string;
            /** Stage */
            stage?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Message */
            message?: string | null;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /** Cached From */
            cached_from?: string | null;
            /** Runtime Ms */
            runtime_ms?: number | null;
            /** Stage Timings */
            stage_timings?: {
                [key: string]: unknown;
            } | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Trace Id */
            trace_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactRef"][];
            /** Logs */
            logs?: components["schemas"]["TaskLog"][] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveHealthResponse"];
                };
            };
        };
    };
    health_ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyHealthResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    prometheus_metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    overview_api_v1_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewStats"];
                };
            };
        };
    };
    upload_studies_api_v1_studies_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_studies_api_v1_studies_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_studies_api_v1_studies_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                modality?: string | null;
                body_part?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StudySummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_study_api_v1_studies__study_uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_demo_api_v1_studies_seed_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySummary"];
                };
            };
        };
    };
    get_series_api_v1_series__series_uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instances_api_v1_series__series_uid__instances_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frame_api_v1_series__series_uid__frames__idx__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_uid: string;
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumbnail_api_v1_series__series_uid__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: {
                enabled_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_ready_api_v1_models__model_id__ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelReadyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_v1_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_model_api_v1_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
                model_id?: string | null;
                /** @description Search task_id / series / model / error */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TaskSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_v1_tasks__task_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_events_api_v1_tasks__task_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_v1_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_task_api_v1_tasks__task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_v1_tasks__task_id__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mask_frame_api_v1_tasks__task_id__mask_frames__slice_index__get: {
        parameters: {
            query?: {
                prefix?: string;
            };
            header?: never;
            path: {
                task_id: string;
                slice_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_tasks__task_id__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
